#!/bin/bash
#
# Usage:
#   clean_bams_v3.sh <regions.bed> <indir> <outdir> <njobs>
#
# Description:
#   Remove unmapped (4), secondary (256), QC failed (512), and duplicate (1024)
#   reads from indel-realigned BAMs, and keep only reads mapped in a proper
#   pair (2) to regions in a BED file (non-repetitive regions in autosomes)
#   using samtools.
#
# Requirements:
#   samtools
#   parallel
#   `autosomes.no_repeats.bed` (previously generated by processing the RepeatMakser output)
#
# Important:
#   Each job uses 4 CPU threads.

# clean indel-realigned BAMs
parallel -j $4 --plus \
  samtools view -@ 4 -b -F 1796 -f 2 -L $1 -o $3/{/..}.clean.bam {} \
  ::: $2/*.realigned.bam

# index clean BAMs
parallel -j $4 samtools index -b {} ::: $3/*.clean.bam
